---
version: '3.8'
services:
  fastapi:
    restart: unless-stopped
    build:
      context: ./Back_end
      dockerfile: Dockerfile
    ports: [24486:35000]
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:  
    - "5432:5432"
  react:
    restart: unless-stopped
    build:
      context: ./Front_end
      dockerfile: Dockerfile
    depends_on: [fastapi]
    ports: [80:80]
  nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Front_end/build:/usr/share/nginx/html
    ports: [35001:80]
    depends_on: [fastapi, react]

networks:
  localnet:    
    driver: bridge